# Generated by Django 3.0.7 on 2020-07-02 19:05

import dinedash.menu.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('uuid',
                 dinedash.menu.fields.ShortUUIDField(blank=True,
                                                     editable=False,
                                                     max_length=22,
                                                     primary_key=True,
                                                     serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('menu',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='menu.Menu')),
            ],
            options={
                'verbose_name_plural': 'menu categories',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='menu.MenuCategory')),
            ],
        ),
        migrations.CreateModel(
            name='AddonSection',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('required', models.BooleanField()),
                ('menu_item',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='menu.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('selection',
                 models.CharField(choices=[('R', 'Radio'),
                                           ('M', 'Multiple Selection')],
                                  default='R',
                                  max_length=1)),
                ('section',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='menu.AddonSection')),
            ],
        ),
    ]
