# Generated by Django 3.0.6 on 2020-05-28 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItemAddon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=150)),
                ("required", models.BooleanField()),
                (
                    "selection",
                    models.CharField(
                        choices=[("R", "Radio"), ("M", "Multiple Selection")],
                        default="R",
                        max_length=1,
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.MenuItem"),
                ),
            ],
        ),
    ]
