# Generated by Django 3.0.7 on 2020-06-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitemaddon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('selection', models.CharField(choices=[('R', 'Radio'), ('M', 'Multiple Selection')], default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AddonSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('required', models.BooleanField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MenuItem')),
            ],
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name_plural': 'menu categories'},
        ),
        migrations.DeleteModel(
            name='MenuItemAddon',
        ),
        migrations.AddField(
            model_name='addon',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.AddonSection'),
        ),
    ]
